name: "First Github action workflow"

on:
  push:
    branches: 
        - master
  pull_request:
    branches: 
        - master
  workflow_dispatch:

jobs:
  sayHello:
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1 of say hello"
      - uses: actions/checkout@v2
      - name: "Step 2 of say hello"
        run: echo "Hello world"
        shell: bash
  sayGoodBye:
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1 of say good bye"
        run: echo "Good bye"
        shell: bash